#!/usr/bin/env bash
# This script loops 1 to 10: "bad luck" on 4, "good luck" on 8, "Best School" otherwise
i=1
while [ "$i" -le 10 ]; do
    if [ "$i" -eq 4 ]; then
        echo "bad luck"
    elif [ "$i" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
