#!/bin/bash
echo $(printf '%o' $(( $(echo $WATER | tr 'water' '01234' | xargs -I{} python3 -c "print(int('{}',5))") + $(echo $STIR | tr 'stir.' '01234' | xargs -I{} python3 -c "print(int('{}',5))") )) | tr '01234567' 'bestchol')
