#!/usr/bin/env bash
# This script displays "To infinity and beyond" and survives SIGTERM signals
trap "echo 'I am invincible!!!'" SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
